# Generated by Django 6.1.1 on 2026-09-30 04:48

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(db_index=True, max_length=100)),
                ('entity_type', models.CharField(blank=True, default='', max_length=50)),
                ('entity_id', models.CharField(blank=True, default='', max_length=64)),
                ('properties', models.JSONField(default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Event',
                'verbose_name_plural': 'Activity Events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'event_name', '-created_at'], name='act_user_evt_date_idx'), models.Index(fields=['event_name', '-created_at'], name='act_name_date_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyStudentAnalytics',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('submissions_count', models.PositiveIntegerField(default=0)),
                ('questions_solved_count', models.PositiveIntegerField(default=0)),
                ('time_spent_minutes', models.PositiveIntegerField(default=0)),
                ('score_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_analytics', to='students.studentprofile')),
            ],
            options={
                'verbose_name': 'Daily Student Analytics',
                'verbose_name_plural': 'Daily Student Analytics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date', '-score_earned'], name='daily_ana_date_score_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'date'), name='unique_student_daily_analytics')],
            },
        ),
    ]
