# Generated by Django 6.1.1 on 2026-09-30 11:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('STUDENT_PERFORMANCE', 'Student Performance'), ('COURSE_STATISTICS', 'Course Statistics'), ('ASSIGNMENT_COMPLETION', 'Assignment Completion'), ('PROJECT_PERFORMANCE', 'Project Performance'), ('MONTHLY_ACTIVITY', 'Monthly Activity'), ('FULL_EXECUTIVE', 'Full Executive Report')], db_index=True, max_length=50)),
                ('format', models.CharField(choices=[('CSV', 'Comma-Separated Values (CSV)'), ('JSON', 'JavaScript Object Notation (JSON)')], default='CSV', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_path', models.CharField(blank=True, default='', max_length=500)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('row_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Export Job',
                'verbose_name_plural': 'Export Jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status', '-created_at'], name='exp_usr_stat_idx'), models.Index(fields=['report_type', 'status'], name='exp_type_stat_idx')],
            },
        ),
    ]
