# Generated by Django 6.1.1 on 2026-09-30 04:48

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed markdown project specifications"
                    ),
                ),
                (
                    "deliverables_instructions",
                    models.TextField(
                        help_text="Instructions for repository and demo submission"
                    ),
                ),
                (
                    "max_score",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("100.00"), max_digits=6
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectSubmission",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "github_repository_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                (
                    "live_demo_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("CHANGES_REQUESTED", "Changes Requested"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="SUBMITTED",
                        max_length=30,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Evaluated project score",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="projects.project",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_submissions",
                        to="students.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Submission",
                "verbose_name_plural": "Project Submissions",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectFile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to="project_files/%Y/%m/")),
                ("file_name", models.CharField(max_length=255)),
                ("file_size_bytes", models.BigIntegerField()),
                ("mime_type", models.CharField(max_length=100)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="projects.projectsubmission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project File",
                "verbose_name_plural": "Project Files",
            },
        ),
        migrations.CreateModel(
            name="ProjectFeedback",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("feedback_text", models.TextField()),
                ("suggested_changes", models.TextField(blank=True, default="")),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Rating on a 1-5 scale", null=True
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="given_project_feedbacks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="projects.projectsubmission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Project Feedback",
                "verbose_name_plural": "Project Feedbacks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="projectsubmission",
            index=models.Index(
                fields=["project", "status"], name="proj_subm_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectsubmission",
            index=models.Index(
                fields=["student", "status"], name="proj_student_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="projectsubmission",
            constraint=models.UniqueConstraint(
                fields=("project", "student"), name="unique_student_project_submission"
            ),
        ),
    ]
