# Generated by Django 6.1.1 on 2026-09-30 04:48

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingQuestion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=280)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], db_index=True, default='EASY', max_length=20)),
                ('problem_statement', models.TextField(help_text='Markdown formatted problem description')),
                ('allowed_languages', models.JSONField(default=list, help_text="e.g. ['python', 'java', 'c', 'cpp', 'javascript']")),
                ('starter_code', models.JSONField(default=dict, help_text="Keyed by language code, e.g. {'python': 'def solution(): pass'}")),
                ('time_limit_seconds', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=4)),
                ('memory_limit_mb', models.PositiveIntegerField(default=128)),
                ('points', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=7)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_questions', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='modules.module')),
            ],
            options={
                'verbose_name': 'Coding Question',
                'verbose_name_plural': 'Coding Questions',
                'ordering': ['module', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CodeSubmission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(db_index=True, max_length=30)),
                ('source_code', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Execution'), ('RUNNING', 'Running'), ('ACCEPTED', 'Accepted'), ('WRONG_ANSWER', 'Wrong Answer'), ('TIME_LIMIT_EXCEEDED', 'Time Limit Exceeded'), ('MEMORY_LIMIT_EXCEEDED', 'Memory Limit Exceeded'), ('COMPILATION_ERROR', 'Compilation Error'), ('RUNTIME_ERROR', 'Runtime Error')], db_index=True, default='PENDING', max_length=30)),
                ('passed_test_cases', models.PositiveIntegerField(default=0)),
                ('total_test_cases', models.PositiveIntegerField(default=0)),
                ('execution_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('peak_memory_kb', models.PositiveIntegerField(blank=True, null=True)),
                ('score_awarded', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('scoring_policy', models.CharField(choices=[('FULL', 'Full Credit'), ('HALF', 'Half Credit'), ('ZERO', 'Zero Credit')], default='ZERO', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_submissions', to='students.studentprofile')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.codingquestion')),
            ],
            options={
                'verbose_name': 'Code Submission',
                'verbose_name_plural': 'Code Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentQuestionProgress',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_solved', models.BooleanField(db_index=True, default=False)),
                ('best_score', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0.00'), max_digits=7)),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('first_solved_at', models.DateTimeField(blank=True, null=True)),
                ('last_submitted_at', models.DateTimeField(auto_now=True)),
                ('best_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assignments.codesubmission')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progresses', to='assignments.codingquestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_progresses', to='students.studentprofile')),
            ],
            options={
                'verbose_name': 'Student Question Progress',
                'verbose_name_plural': 'Student Question Progresses',
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_data', models.TextField(help_text='Standard input payload')),
                ('expected_output', models.TextField(help_text='Expected standard output')),
                ('is_visible', models.BooleanField(db_index=True, default=True, help_text='True for public samples, False for hidden grading tests')),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='assignments.codingquestion')),
            ],
            options={
                'verbose_name': 'Test Case',
                'verbose_name_plural': 'Test Cases',
                'ordering': ['question', '-is_visible', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PASSED', 'Passed'), ('FAILED', 'Failed'), ('TIME_LIMIT_EXCEEDED', 'Time Limit Exceeded'), ('MEMORY_LIMIT_EXCEEDED', 'Memory Limit Exceeded'), ('RUNTIME_ERROR', 'Runtime Error'), ('COMPILATION_ERROR', 'Compilation Error')], db_index=True, max_length=30)),
                ('stdout', models.TextField(blank=True, default='')),
                ('stderr', models.TextField(blank=True, default='')),
                ('execution_time_seconds', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('memory_kb', models.PositiveIntegerField(blank=True, null=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_results', to='assignments.codesubmission')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_results', to='assignments.testcase')),
            ],
            options={
                'verbose_name': 'Execution Result',
                'verbose_name_plural': 'Execution Results',
            },
        ),
        migrations.AddIndex(
            model_name='codingquestion',
            index=models.Index(fields=['module', 'difficulty'], name='question_mod_diff_idx'),
        ),
        migrations.AddIndex(
            model_name='codingquestion',
            index=models.Index(fields=['module', 'order'], name='question_mod_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='codingquestion',
            constraint=models.UniqueConstraint(fields=('module', 'slug'), name='unique_module_question_slug'),
        ),
        migrations.AddConstraint(
            model_name='codingquestion',
            constraint=models.CheckConstraint(condition=models.Q(('points__gt', Decimal('0.00'))), name='positive_question_points'),
        ),
        migrations.AddIndex(
            model_name='codesubmission',
            index=models.Index(fields=['student', 'question', '-submitted_at'], name='subm_student_q_date_idx'),
        ),
        migrations.AddIndex(
            model_name='codesubmission',
            index=models.Index(fields=['question', 'status'], name='subm_question_status_idx'),
        ),
        migrations.AddIndex(
            model_name='codesubmission',
            index=models.Index(fields=['status', 'submitted_at'], name='subm_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='studentquestionprogress',
            index=models.Index(fields=['student', 'is_solved'], name='q_prog_student_solved_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentquestionprogress',
            constraint=models.UniqueConstraint(fields=('student', 'question'), name='unique_student_question_progress'),
        ),
        migrations.AddConstraint(
            model_name='studentquestionprogress',
            constraint=models.CheckConstraint(condition=models.Q(('best_score__gte', Decimal('0.00'))), name='non_negative_question_best_score'),
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['question', 'is_visible'], name='testcase_q_vis_idx'),
        ),
        migrations.AddConstraint(
            model_name='executionresult',
            constraint=models.UniqueConstraint(fields=('submission', 'test_case'), name='unique_submission_testcase_result'),
        ),
    ]
