# Generated by Django 5.1.15 on 2026-10-05 04:26

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("students", "0002_studentprofile_attendance_percentage_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlacementDrive",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_name", models.CharField(db_index=True, max_length=200)),
                (
                    "company_code",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. GQT-TCS-2026",
                        max_length=50,
                    ),
                ),
                (
                    "company_logo_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                (
                    "role",
                    models.CharField(
                        help_text="e.g. Full Stack Developer, SDE-1", max_length=200
                    ),
                ),
                (
                    "skills",
                    models.TextField(
                        help_text="Required skills, comma-separated e.g. React, Node.js, Python, SQL"
                    ),
                ),
                (
                    "location",
                    models.CharField(default="Bengaluru, Karnataka", max_length=200),
                ),
                (
                    "mode_of_work",
                    models.CharField(
                        choices=[
                            ("ON_SITE", "On-site"),
                            ("REMOTE", "Remote"),
                            ("HYBRID", "Hybrid"),
                        ],
                        db_index=True,
                        default="ON_SITE",
                        max_length=20,
                    ),
                ),
                (
                    "stipend_or_ctc",
                    models.CharField(
                        help_text="e.g. 6.5 - 8.5 LPA or 25,000/month Internship + PPO",
                        max_length=150,
                    ),
                ),
                (
                    "bond_period",
                    models.CharField(
                        default="None",
                        help_text="e.g. None, 1 Year Service Agreement, 2 Years",
                        max_length=150,
                    ),
                ),
                (
                    "eligibility_criteria",
                    models.TextField(
                        default="B.Tech/BE (CSE/ISE/ECE/IT), Min 60% or 6.0 CGPA, No active backlogs",
                        help_text="Detailed academic and stream criteria",
                    ),
                ),
                (
                    "min_cgpa",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Minimum CGPA required (0 for no cutoff)",
                        max_digits=4,
                    ),
                ),
                (
                    "eligible_batches",
                    models.CharField(
                        default="2025, 2026",
                        help_text="Eligible graduating batches",
                        max_length=255,
                    ),
                ),
                (
                    "job_description",
                    models.TextField(
                        help_text="Full job profile, responsibilities, and interview process"
                    ),
                ),
                ("application_deadline", models.DateTimeField(db_index=True)),
                (
                    "drive_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Scheduled drive or interview date",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPCOMING", "Upcoming"),
                            ("ONGOING", "Active / Ongoing"),
                            ("CLOSED", "Closed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="ONGOING",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_placement_drives",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Placement Drive",
                "verbose_name_plural": "Placement Drives",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlacementApplication",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("APPLIED", "Applied"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("SHORTLISTED", "Shortlisted"),
                            ("SELECTED", "Selected / Offered"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="APPLIED",
                        max_length=30,
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Internal feedback / assessment notes",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Reason shared or logged if rejected",
                    ),
                ),
                ("student_name", models.CharField(max_length=150)),
                ("student_id_number", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone_number",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                (
                    "college_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "branch",
                    models.CharField(
                        blank=True, default="Computer Science", max_length=100
                    ),
                ),
                ("graduation_year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "cgpa_or_percentage",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "resume_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Google Drive / Cloud storage link",
                        max_length=500,
                    ),
                ),
                (
                    "portfolio_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                ("github_url", models.URLField(blank=True, default="", max_length=500)),
                (
                    "linkedin_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                ("skills_summary", models.TextField(blank=True, default="")),
                (
                    "cover_note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Student's message or statement of intent",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_placement_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placement_applications",
                        to="students.studentprofile",
                    ),
                ),
                (
                    "drive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="placements.placementdrive",
                    ),
                ),
            ],
            options={
                "verbose_name": "Placement Application",
                "verbose_name_plural": "Placement Applications",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.AddIndex(
            model_name="placementdrive",
            index=models.Index(
                fields=["status", "is_active", "-application_deadline"],
                name="drive_status_active_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="placementdrive",
            index=models.Index(
                fields=["company_name", "role"], name="drive_comp_role_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="placementapplication",
            index=models.Index(fields=["drive", "status"], name="drive_app_status_idx"),
        ),
        migrations.AddIndex(
            model_name="placementapplication",
            index=models.Index(
                fields=["student", "status"], name="stud_app_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="placementapplication",
            index=models.Index(
                fields=["status", "-submitted_at"], name="app_status_time_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="placementapplication",
            constraint=models.UniqueConstraint(
                fields=("drive", "student"), name="unique_student_drive_application"
            ),
        ),
    ]
