# Generated by Django 6.1.1 on 2026-09-30 04:48

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "content",
                    models.TextField(help_text="Markdown announcement content"),
                ),
                (
                    "target_batch",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Empty string indicates global announcement",
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("NORMAL", "Normal"),
                            ("HIGH", "High"),
                            ("URGENT", "Urgent"),
                        ],
                        db_index=True,
                        default="NORMAL",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_announcements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Announcement",
                "verbose_name_plural": "Announcements",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "target_batch", "-created_at"],
                        name="ann_active_batch_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("SUBMISSION_GRADED", "Submission Graded"),
                            ("MODULE_UNLOCKED", "Module Unlocked"),
                            ("PROJECT_FEEDBACK", "Project Feedback"),
                            ("STREAK_ALERT", "Streak Alert"),
                            ("SYSTEM_NOTICE", "System Notice"),
                        ],
                        default="SYSTEM_NOTICE",
                        max_length=40,
                    ),
                ),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "action_url",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read", "-created_at"],
                        name="notif_recip_read_idx",
                    )
                ],
            },
        ),
    ]
