# Generated by Django 6.1.1 on 2026-09-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('SUBMISSION_GRADED', 'Submission Graded'), ('MODULE_UNLOCKED', 'Module Unlocked'), ('PROJECT_FEEDBACK', 'Project Feedback'), ('STREAK_ALERT', 'Streak Alert'), ('DEADLINE_REMINDER', 'Deadline Reminder'), ('TASK_COMPLETED', 'Task Completed'), ('SYSTEM_NOTICE', 'System Notice')], default='SYSTEM_NOTICE', max_length=40),
        ),
    ]
