# Generated by Django 6.1.1 on 2026-09-30 04:48

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoreRecord",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("ASSIGNMENT", "Coding Assignment"),
                            ("DAILY_TASK", "Daily Task"),
                            ("PROJECT", "Capstone Project"),
                            ("STREAK_BONUS", "Streak Bonus"),
                            ("ADMIN_ADJUSTMENT", "Administrative Adjustment"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "source_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="ID of QuestionSubmission, TaskCompletion, etc.",
                    ),
                ),
                ("points", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "policy_applied",
                    models.CharField(
                        choices=[
                            ("FULL", "Full Credit"),
                            ("HALF", "Half Credit"),
                            ("ZERO", "Zero Credit"),
                            ("MANUAL", "Manual Review"),
                        ],
                        default="FULL",
                        max_length=20,
                    ),
                ),
                ("awarded_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "awarded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="awarded_scores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_records",
                        to="students.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Score Record",
                "verbose_name_plural": "Score Records",
                "ordering": ["-awarded_at"],
            },
        ),
        migrations.CreateModel(
            name="ScoreEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("SUBMISSION_EVALUATED", "Submission Evaluated"),
                            ("ADMIN_OVERRIDE", "Admin Override"),
                            ("STREAK_BONUS_ADDED", "Streak Bonus Added"),
                            ("DEDUCTION", "Score Deduction"),
                            ("RECALCULATION", "Recalculation"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("delta", models.DecimalField(decimal_places=2, max_digits=7)),
                ("reason", models.CharField(max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_events",
                        to="students.studentprofile",
                    ),
                ),
                (
                    "score_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="scoring.scorerecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Score Event",
                "verbose_name_plural": "Score Events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeaderboardSnapshot",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("snapshot_date", models.DateField(db_index=True)),
                ("batch_code", models.CharField(db_index=True, max_length=50)),
                ("total_score", models.DecimalField(decimal_places=2, max_digits=10)),
                ("global_rank", models.PositiveIntegerField(db_index=True)),
                ("batch_rank", models.PositiveIntegerField(db_index=True)),
                ("streak_days", models.PositiveIntegerField(default=0)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_snapshots",
                        to="students.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Leaderboard Snapshot",
                "verbose_name_plural": "Leaderboard Snapshots",
                "ordering": ["snapshot_date", "global_rank"],
                "indexes": [
                    models.Index(
                        fields=["snapshot_date", "batch_code", "batch_rank"],
                        name="lb_snap_date_batch_idx",
                    ),
                    models.Index(
                        fields=["snapshot_date", "global_rank"],
                        name="lb_snap_date_global_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("snapshot_date", "student"),
                        name="unique_daily_student_leaderboard_snapshot",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="scorerecord",
            index=models.Index(
                fields=["student", "source_type"], name="score_student_src_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scorerecord",
            index=models.Index(
                fields=["source_type", "source_id"], name="score_source_lookup_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="scorerecord",
            constraint=models.UniqueConstraint(
                fields=("student", "source_type", "source_id"),
                name="unique_student_source_score_record",
            ),
        ),
        migrations.AddIndex(
            model_name="scoreevent",
            index=models.Index(
                fields=["student", "created_at"], name="score_event_student_date_idx"
            ),
        ),
    ]
