# Generated by Django 6.1.1 on 2026-09-30 04:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginActivity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifier', models.CharField(db_index=True, max_length=255)),
                ('login_type', models.CharField(choices=[('EMAIL_PASSWORD', 'Email & Password'), ('MOBILE_OTP', 'Mobile & OTP'), ('TOKEN_REFRESH', 'Token Refresh')], max_length=30)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED_CREDENTIALS', 'Failed Credentials'), ('FAILED_OTP', 'Failed OTP'), ('LOCKED', 'Account Locked')], db_index=True, max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('failure_reason', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Login Activity',
                'verbose_name_plural': 'Login Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mobile_number', models.CharField(db_index=True, max_length=20)),
                ('otp_hash', models.CharField(max_length=128)),
                ('purpose', models.CharField(choices=[('LOGIN', 'Login Authentication'), ('PASSWORD_RESET', 'Password Reset'), ('PHONE_VERIFY', 'Phone Verification')], default='LOGIN', max_length=30)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('is_used', models.BooleanField(db_index=True, default=False)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'verbose_name': 'OTP Verification',
                'verbose_name_plural': 'OTP Verifications',
            },
        ),
        migrations.CreateModel(
            name='PasswordResetRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(db_index=True, max_length=128, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('is_used', models.BooleanField(db_index=True, default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Password Reset Request',
                'verbose_name_plural': 'Password Reset Requests',
            },
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Audit Log', 'verbose_name_plural': 'Audit Logs'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name'], 'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor', 'created_at'], name='audit_actor_created_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['target_model', 'target_id'], name='audit_target_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'is_active'], name='user_email_active_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['mobile_number', 'is_active'], name='user_mobile_active_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='user_role_active_idx'),
        ),
        migrations.AddField(
            model_name='loginactivity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='otpverification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passwordresetrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_resets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='loginactivity',
            index=models.Index(fields=['user', 'created_at'], name='login_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='loginactivity',
            index=models.Index(fields=['ip_address', 'created_at'], name='login_ip_created_idx'),
        ),
        migrations.AddIndex(
            model_name='loginactivity',
            index=models.Index(fields=['status', 'created_at'], name='login_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['mobile_number', 'is_used', 'expires_at'], name='otp_mobile_used_exp_idx'),
        ),
        migrations.AddConstraint(
            model_name='otpverification',
            constraint=models.CheckConstraint(condition=models.Q(('attempts__lte', models.F('max_attempts'))), name='otp_attempts_within_limit'),
        ),
        migrations.AddIndex(
            model_name='passwordresetrequest',
            index=models.Index(fields=['token_hash', 'is_used'], name='pwd_reset_token_used_idx'),
        ),
        migrations.AddIndex(
            model_name='passwordresetrequest',
            index=models.Index(fields=['user', 'is_used'], name='pwd_reset_user_used_idx'),
        ),
    ]
