# Generated by Django 5.1.15 on 2026-10-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_loginactivity_otpverification_passwordresetrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='avatar_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='designation',
            field=models.CharField(blank=True, default='Portal Administrator', max_length=100),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='full_name',
            field=models.CharField(blank=True, default='Administrator', max_length=150),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
