# Generated by Django 6.1.1 on 2026-10-09 10:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_adminprofile_avatar_url_adminprofile_bio_and_more'),
        ('students', '0005_college_studentprofile_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator / Staff'), ('STUDENT', 'Student'), ('TPO', 'Training & Placement Officer')], db_index=True, default='STUDENT', max_length=20),
        ),
        migrations.CreateModel(
            name='TPOProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, default='', max_length=150)),
                ('designation', models.CharField(blank=True, default='Training & Placement Officer', max_length=100)),
                ('department', models.CharField(blank=True, default='Training & Placement Cell', max_length=100)),
                ('phone_number', models.CharField(blank=True, default='', max_length=30)),
                ('bio', models.TextField(blank=True, default='')),
                ('avatar_url', models.CharField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Controls active authorization status for this institutional college.')),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tpos', to=settings.AUTH_USER_MODEL)),
                ('college', models.ForeignKey(blank=True, help_text='Institutional college explicitly assigned by Administrator.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tpo_officers', to='students.college')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_tpos', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tpo_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TPO Profile',
                'verbose_name_plural': 'TPO Profiles',
                'indexes': [models.Index(fields=['college', 'is_active'], name='tpo_college_active_idx'), models.Index(fields=['user', 'is_active'], name='tpo_user_active_idx')],
            },
        ),
    ]
