# Generated by Django 6.1.1 on 2026-09-30 04:48

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('scheduled_date', models.DateField(db_index=True, unique=True)),
                ('points', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_tasks', to='assignments.codingquestion')),
            ],
            options={
                'verbose_name': 'Daily Task',
                'verbose_name_plural': 'Daily Tasks',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentTask',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_completed', models.BooleanField(default=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('score_awarded', models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_completions', to='students.studentprofile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Student Task Completion',
                'verbose_name_plural': 'Student Task Completions',
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['student', 'completed_at'], name='student_task_comp_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'task'), name='unique_student_daily_task_completion')],
            },
        ),
    ]
