# Generated by Django 6.1.1 on 2026-10-06 10:59

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
        ("modules", "0001_initial"),
        ("students", "0003_studentprofile_last_activity_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecordedClass",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=280)),
                ("description", models.TextField(blank=True, default="")),
                ("order_index", models.PositiveIntegerField(db_index=True, default=1)),
                (
                    "video_source_type",
                    models.CharField(
                        choices=[
                            ("YOUTUBE", "YouTube Link"),
                            ("DIRECT", "Direct Upload / Video File"),
                            ("EXTERNAL", "External URL / Stream"),
                        ],
                        db_index=True,
                        default="YOUTUBE",
                        max_length=20,
                    ),
                ),
                (
                    "youtube_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                (
                    "youtube_video_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        help_text="Direct video upload for self-hosted / Supabase storage video lectures",
                        null=True,
                        upload_to="courses/videos/%Y/%m/",
                    ),
                ),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Direct streaming URL or cloud storage URL",
                        max_length=1000,
                    ),
                ),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                (
                    "duration_formatted",
                    models.CharField(blank=True, default="00:00", max_length=20),
                ),
                (
                    "thumbnail_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                (
                    "is_preview",
                    models.BooleanField(
                        default=False,
                        help_text="Explicit preview override flag. Note: First 5 videos are always free preview.",
                    ),
                ),
                ("is_published", models.BooleanField(db_index=True, default=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Markdown lecture notes or syllabus summary",
                    ),
                ),
                (
                    "resources_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Repository or supplementary materials URL",
                        max_length=500,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recorded_classes",
                        to="courses.course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_recorded_classes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_classes",
                        to="modules.module",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recorded Class",
                "verbose_name_plural": "Recorded Classes",
                "ordering": ["order_index", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentRecordedClassProgress",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("last_position_seconds", models.PositiveIntegerField(default=0)),
                ("is_completed", models.BooleanField(db_index=True, default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recorded_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_progresses",
                        to="courses.recordedclass",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recorded_class_progresses",
                        to="students.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Recorded Class Progress",
                "verbose_name_plural": "Student Recorded Class Progresses",
            },
        ),
        migrations.AddIndex(
            model_name="recordedclass",
            index=models.Index(
                fields=["course", "is_published", "order_index"],
                name="rec_class_course_pub_ord_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recordedclass",
            index=models.Index(
                fields=["course", "order_index"], name="rec_class_course_ord_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="recordedclass",
            constraint=models.UniqueConstraint(
                fields=("course", "slug"), name="unique_course_recorded_class_slug"
            ),
        ),
        migrations.AddIndex(
            model_name="studentrecordedclassprogress",
            index=models.Index(
                fields=["student", "is_completed"], name="rec_prog_student_comp_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentrecordedclassprogress",
            index=models.Index(
                fields=["recorded_class", "is_completed"],
                name="rec_prog_class_comp_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="studentrecordedclassprogress",
            constraint=models.UniqueConstraint(
                fields=("student", "recorded_class"),
                name="unique_student_recorded_class_progress",
            ),
        ),
    ]
