# Generated by Django 6.1.1 on 2026-09-30 04:48

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=180)),
                ("order_index", models.PositiveSmallIntegerField(db_index=True)),
                ("summary", models.TextField(blank=True, default="")),
                ("lecture_content", models.TextField(blank=True, default="")),
                (
                    "passing_percentage",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("80.00"), max_digits=5
                    ),
                ),
                ("is_published", models.BooleanField(db_index=True, default=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Curriculum Module",
                "verbose_name_plural": "Curriculum Modules",
                "ordering": ["course", "order_index"],
            },
        ),
        migrations.CreateModel(
            name="ModulePrerequisite",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prerequisites",
                        to="modules.module",
                    ),
                ),
                (
                    "prerequisite_module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependent_modules",
                        to="modules.module",
                    ),
                ),
            ],
            options={
                "verbose_name": "Module Prerequisite",
                "verbose_name_plural": "Module Prerequisites",
            },
        ),
        migrations.CreateModel(
            name="StudentModuleProgress",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("LOCKED", "Locked"),
                            ("UNLOCKED", "Unlocked"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                        ],
                        db_index=True,
                        default="LOCKED",
                        max_length=20,
                    ),
                ),
                (
                    "score_percentage",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                ("unlocked_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("unlocked_by_override", models.BooleanField(default=False)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_progresses",
                        to="modules.module",
                    ),
                ),
                (
                    "override_admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="granted_module_overrides",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_progresses",
                        to="students.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Module Progress",
                "verbose_name_plural": "Student Module Progresses",
            },
        ),
        migrations.AddConstraint(
            model_name="module",
            constraint=models.UniqueConstraint(
                fields=("course", "order_index"), name="unique_course_module_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="module",
            constraint=models.UniqueConstraint(
                fields=("course", "slug"), name="unique_course_module_slug"
            ),
        ),
        migrations.AddConstraint(
            model_name="module",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("passing_percentage__gte", Decimal("0.00")),
                    ("passing_percentage__lte", Decimal("100.00")),
                ),
                name="valid_module_passing_percentage",
            ),
        ),
        migrations.AddConstraint(
            model_name="moduleprerequisite",
            constraint=models.UniqueConstraint(
                fields=("module", "prerequisite_module"),
                name="unique_module_prerequisite",
            ),
        ),
        migrations.AddConstraint(
            model_name="moduleprerequisite",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("module", models.F("prerequisite_module")), _negated=True
                ),
                name="prevent_self_prerequisite",
            ),
        ),
        migrations.AddIndex(
            model_name="studentmoduleprogress",
            index=models.Index(
                fields=["student", "status"], name="mod_prog_student_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentmoduleprogress",
            index=models.Index(
                fields=["module", "status"], name="mod_prog_module_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentmoduleprogress",
            constraint=models.UniqueConstraint(
                fields=("student", "module"), name="unique_student_module_progress"
            ),
        ),
        migrations.AddConstraint(
            model_name="studentmoduleprogress",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("score_percentage__gte", Decimal("0.00")),
                    ("score_percentage__lte", Decimal("100.00")),
                ),
                name="valid_module_score_percentage",
            ),
        ),
    ]
