# Generated by Django 6.1.1 on 2026-09-30 04:48

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "student_id_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("full_name", models.CharField(max_length=150)),
                ("batch_code", models.CharField(db_index=True, max_length=50)),
                (
                    "college_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("graduation_year", models.PositiveIntegerField(blank=True, null=True)),
                ("current_streak_days", models.PositiveIntegerField(default=0)),
                ("highest_streak_days", models.PositiveIntegerField(default=0)),
                (
                    "total_points",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                    ),
                ),
                ("avatar_url", models.URLField(blank=True, default="", max_length=500)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Profile",
                "verbose_name_plural": "Student Profiles",
                "indexes": [
                    models.Index(
                        fields=["batch_code", "-total_points"], name="batch_points_idx"
                    ),
                    models.Index(fields=["-total_points"], name="global_points_idx"),
                    models.Index(
                        fields=["user", "batch_code"], name="student_user_batch_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("total_points__gte", Decimal("0.00"))),
                        name="non_negative_student_points",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "current_streak_days__lte",
                                models.F("highest_streak_days"),
                            )
                        ),
                        name="current_streak_lte_highest",
                    ),
                ],
            },
        ),
    ]
