# Generated by Django 6.1.1 on 2026-10-01 11:58

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="attendance_percentage",
            field=models.DecimalField(
                db_index=True, decimal_places=2, default=Decimal("100.00"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="attended_classes",
            field=models.PositiveIntegerField(default=45),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="bio",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="branch",
            field=models.CharField(
                blank=True, default="Computer Science", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="course_opted",
            field=models.CharField(
                blank=True,
                default="Full Stack Software & Assessment Track",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="github_url",
            field=models.URLField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="linkedin_url",
            field=models.URLField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="total_classes",
            field=models.PositiveIntegerField(default=45),
        ),
        migrations.CreateModel(
            name="AttendanceRecord",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                (
                    "session_title",
                    models.CharField(
                        default="Daily Training & Coding Lab", max_length=200
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Present"),
                            ("ABSENT", "Absent"),
                            ("LATE", "Late"),
                            ("EXCUSED", "Excused"),
                        ],
                        default="PRESENT",
                        max_length=20,
                    ),
                ),
                ("remarks", models.CharField(blank=True, default="", max_length=255)),
                (
                    "student_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="students.studentprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Record",
                "verbose_name_plural": "Attendance Records",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["student_profile", "date"],
                        name="attendance_stud_date_idx",
                    ),
                    models.Index(
                        fields=["date", "status"], name="attendance_date_status_idx"
                    ),
                ],
            },
        ),
    ]
