# Generated by Django 5.1.15 on 2026-10-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentprofile_attendance_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='last_activity_date',
            field=models.DateField(blank=True, help_text='Date of last solved problem for streak tracking', null=True),
        ),
    ]
